[PB-1901]: feat/add billing account section
internxt/drive-web pull request #1065
Opened 2024-03-26 16:20 UTC by rafijv

2024-03-27 10:55 UTC, CandelR requested changes
@rafijv Check the design in figma, when it is a free account it does not meet the Billing plan states https://www.figma.com/file/62hpKnJYlxUN77HUECXAlF/Drive-Web?type=design&node-id=10293-1272&mode=design&t=NYmm8OxfCFz0TWms-0 use cases.

2024-04-02 15:59 UTC, rafijv commented
> @rafijv Check the design in figma, when it is a free account it does not meet the Billing plan states https://www.figma.com/file/62hpKnJYlxUN77HUECXAlF/Drive-Web?type=design&node-id=10293-1272&mode=design&t=NYmm8OxfCFz0TWms-0 use cases.

Done!

2024-04-04 06:10 UTC, CandelR requested changes
Cool, just need to adjust the margins of what I have marked in the image and the background colour of the Card when it is free account is different. 
https://www.figma.com/file/62hpKnJYlxUN77HUECXAlF/Drive-Web?type=design&node-id=10293-1272&mode=design&t=OpDpZiNEp22MEo97-0
[Screenshot](https://gyazo.com/29381a7eefb0f2acfa42ec1736a11f40)

2024-04-04 10:46 UTC, CandelR approved these changes

2024-04-04 11:03 UTC, merged