[PB-2979]: fix/share dialog and migrate recents endpoint to new API
internxt/drive-web pull request #1308
Opened 2024-10-08 15:24 UTC by masterprog-cmd

- Fix the Shared dialog for items - Show the password if the item has
- Migrate the Recents endpoints to the new API
- Display the shared icon for shared items in Recents

2024-10-08 15:35 UTC, masterprog-cmd commented
⚠️  Depends on the following PRs:
- SDK: https://github.com/internxt/sdk/pull/249
- Drive server WIP: https://github.com/internxt/drive-server-wip/pull/409

2024-10-15 15:13 UTC, CandelR requested changes

2024-10-15 15:13 UTC, CandelR commented on src/app/i18n/locales/en.json
> -    "errorApplyingCoupon": "Something went wrong while applying the coupon",
why has this translation been removed?

2024-10-15 15:13 UTC, CandelR commented on src/app/drive/components/DriveExplorer/DriveExplorer.tsx
>    }, [currentFolderId]);
Remember to add `fetchFolderContent` to dependency array

2024-10-16 06:38 UTC, xabg2 commented on src/app/i18n/locales/en.json
> -    "errorApplyingCoupon": "Something went wrong while applying the coupon",
It was duplicated. You can find it above the `invalidTaxIdsProvided` error.

2024-10-16 10:23 UTC, CandelR approved these changes

2024-10-16 11:56 UTC, Jona-Internxt approved these changes

2024-10-16 13:07 UTC, merged