[MKT-472]: Updating Features Banner
internxt/drive-web pull request #1347
Opened 2024-11-08 08:15 UTC by jaaaaavier

Updated Features Banner color and added a new style for the design

2024-11-08 16:10 UTC, xabg2 requested changes

2024-11-08 16:10 UTC, xabg2 commented on src/app/banners/BannerManager.ts
> +    this.bannerItemInLocalStorage = localStorageService.get(BANNER_NAME_IN_LOCAL_STORAGE);
Change it in onCloseBanner too.

2024-11-08 16:11 UTC, xabg2 commented
@jaaaaavier check the Sonarcloud issue

2024-11-11 10:21 UTC, xabg2 approved these changes

2024-11-11 10:28 UTC, CandelR approved these changes

2024-11-11 10:56 UTC, merged