[PB-3313]: feat/update workspace members
internxt/drive-web pull request #1355
Opened 2024-11-15 11:12 UTC by xabg2

Allowing the owner of a workspace to update the members. This will update the billing price for the next cycle and will increase/decrease the total workspace storage (owner storage).

2024-11-15 15:27 UTC, xabg2 commented
This PR needs this [SDK version](https://github.com/internxt/sdk/pull/259).

2024-11-18 16:14 UTC, TamaraFinogina approved these changes
All hybrid encryption flags are set to 'false', so Kyber keys should never be used and can be empty strings

2024-11-19 15:56 UTC, CandelR requested changes

2024-11-19 15:56 UTC, CandelR commented on src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
> +  const [updatedAmountOfSeats, setUpdatedAmountOfSeats] = useState<number | undefined>(
I think `newAmoutOfSeats` is better understood than updated, maybe a bit ambiguous.

2024-11-19 15:56 UTC, CandelR commented on src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
> +  const [joinedMembersInWorkspace, setJoinedMembersInWorkspace] = useState<WorkspaceUser[]>();
I think that "currentWorkspaceMembers" it is more clear 🤔, what do you think?

2024-11-19 15:56 UTC, CandelR commented on src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
> +  };
What happens if the call throws an error? Handle it
This not display any loader while is loading the users?

2024-11-19 15:56 UTC, CandelR commented on src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
> +    }
If the reason for not updating members is known, it would be better to display descriptive messages to inform the user that he/she cannot update members

2024-11-19 15:56 UTC, CandelR commented on src/app/newSettings/Sections/Workspace/Billing/UpdateMembersCard.tsx
> +  onChangeMembersButtonClicked?: () => void;
Does it make sense to make it optional?

2024-11-19 15:56 UTC, CandelR commented on src/app/newSettings/Sections/Workspace/Billing/UpdateMembersCard.tsx
> +  plan: PlanState;
pass directly the necessary field, it isn't necessary pass al the object to obtain the field that gonna display comoponente.

2024-11-19 15:56 UTC, CandelR commented on src/app/newSettings/Sections/Workspace/Billing/components/UpdateMembers/ConfirmUpdateMembersModal.tsx
> +export const ConfirmUpdateMembersModal = ({
`Confirm` seems to me to be superfluous, I think that`UpdateMembersModal` it is already understood, in the modal the user already chooses whether to confirm the change or to keep the members.

2024-11-19 15:56 UTC, CandelR commented on src/app/newSettings/Sections/Workspace/Billing/components/UpdateMembers/UpdateMembersModal.tsx
> +const UpdateMembersCardAndSlider = ({
I think that`UpdateMembersCard` is a good name. 
For example, when others card has inputs or other elements the name of the component is not `UpdateMemberCardAnInputs` 😄

2024-11-19 15:56 UTC, CandelR commented on src/app/newSettings/Sections/Workspace/Billing/components/UpdateMembers/UpdateMembersModal.tsx
> +  const minimumSeats = Math.max(actualMembersInWorkspace, minimumAllowedSeats);
why this extra logic and not add the required `minimumAllowedSeats` directly to seats object?

2024-11-19 16:11 UTC, xabg2 commented on src/app/newSettings/Sections/Workspace/Billing/components/UpdateMembers/ConfirmUpdateMembersModal.tsx
> +export const ConfirmUpdateMembersModal = ({
There are 2 different modals, one to pick the new members and another one to confirm the choose.

2024-11-20 15:42 UTC, CandelR approved these changes

2024-11-22 10:39 UTC, merged