[_]: feat/update-eslint
internxt/drive-web pull request #1360
Opened 2024-11-22 18:26 UTC by larryrider

- Updated ESLint dependencies
- Added eslint fixes and ignores

2024-12-10 08:20 UTC, CandelR requested changes
Reviewed! @larry-internxt If you can and see that it is feasible, remove unused variables to avoid the use of adding exceptions to eslint rules

2024-12-10 08:20 UTC, CandelR commented on eslint.config.mjs
> +    pluginCypress.configs.recommended,
cypress has been removed

2024-12-10 08:20 UTC, CandelR commented on eslint.config.mjs
> +            "@typescript-eslint/no-explicit-any": "warn",
maybe some more concrete rules to not disable the max in the line and empty functions so that the code doesn't get dirty over time would be good

2024-12-10 08:20 UTC, CandelR commented on src/app/auth/components/SignUp/SignUp.tsx
>    const [view, setView] = useState<Views>('signUp');
if this is unused, remove it instead of add eslint disable rule

2024-12-10 08:20 UTC, CandelR commented on src/app/core/components/Sidenav/WorkspaceSelector.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Same here, remove unused vars instead add this rule

2024-12-10 08:20 UTC, CandelR commented on src/app/core/services/navigation.service.ts
> +      instance.push(`${navigationService.history.location.pathname}?workspaceid=${workspaceUuid}`);
fixed in another PR

2024-12-10 08:20 UTC, CandelR commented on src/app/core/services/navigation.service.ts
> +      instance.push(navigationService.history.location.pathname);
fixed in another PR

2024-12-10 08:20 UTC, CandelR commented on src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerGridItem/DriveExplorerGridItem.tsx
> +        {/*eslint-disable-next-line @typescript-eslint/no-unused-vars*/}
same here, remove unused var

2024-12-10 08:20 UTC, CandelR commented on src/app/drive/components/FileViewer/components/TopBarActions.tsx
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
same, remve unused vars

2024-12-10 08:20 UTC, CandelR commented on src/app/drive/components/FileViewer/viewers/FileAudioViewer/FileAudioViewer.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
remve unused vars

2024-12-10 08:20 UTC, CandelR commented on src/app/drive/services/download.service/downloadFile.ts
> +  PatchedStreamApi = 'PatchedStreamApi',
Have you checked that this change doesn't break anything?

2024-12-10 08:20 UTC, CandelR commented on src/app/drive/services/folder.service/uploadFolderInput.service.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
remove unused vars

2024-12-10 08:20 UTC, CandelR commented on src/app/payment/services/checkout.service.ts
> +//const IS_PRODUCTION = envService.isProduction();
remove this commented lines

2024-12-10 08:20 UTC, CandelR commented on src/app/share/views/SharedLinksView/hooks/useFetchSharedData.tsx
> +  //const defaultTeamId = selectedWorkspace?.workspace.defaultTeamId;
remove this commented line

2024-12-10 08:20 UTC, CandelR commented on src/app/store/slices/storage/storage.thunks/fetchDialogContentThunk.ts
> +    .addCase(fetchDialogContentThunk.rejected, (/*state, action*/) => {
remove commented code

2024-12-10 08:20 UTC, CandelR commented on test/e2e/cypress/integration/unauthorized.spec.ts
>  describe('Unauthorized user', () => {
all cypress e2e tests has been removed

2024-12-12 10:47 UTC, larryrider commented
As there will be more conflicts, I have made a new PR where only the dependency is updated, so when it will be resumed, the asignee will be the one who will have to fix the errors that arise then

New PR: https://github.com/internxt/drive-web/pull/1384

2024-12-12 10:47 UTC, closed without merging