[PB-3079] switch to argon2
internxt/drive-web pull request #1372
Opened 2024-11-28 14:37 UTC by TamaraFinogina

PR switches drive-web to Argon2

We now use hash = PBKDF2(pwd, salt). Unfortunately, the parameters are outdated, so we need to upgrade. The idea is to compute Argon2 for all new users and update the hash after login for old ones.

For that, passToHash works as follows:

    If no salt is given (new user), then it samples argon_salt, computes hash = Argon2 ( pwd, argon_salt) and sends (hash, 'argon2id$argoin_salt) to the database
    if salt starts with argon2id$, then it's already migrated user and we compute hash = Argon2( pwd, argon_salt)
    Else, then it's the user that hasn't migrated yet. We compute hash = PBKDF2(pwd, salt)

NOTE: Argon2 follows password [hash competition output format](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md): the output will be $argon2id$v=19$m=65536,t=2,p=1$gZiV/M1gPc22ElAH/Jh1Hw$CWOrkoo7oJBQ/iyh7uJ0LO2aLEfrHwTWllSAxT0zRno or the same line but in HEX.

2024-11-29 12:14 UTC, TamaraFinogina commented on src/app/crypto/services/utils.ts
> + * Argon2id parameters taken from RFC9106 (variant for memory-constrained environments)
@sg-gs. Specs for Argon2  (RFC [9106)](https://www.rfc-editor.org/rfc/rfc9106) offer 2 options:

1. Argon2id with t=1 iteration, p=4 lanes, m=2^(21) (2 GiB of RAM), 128-bit salt, and 256-bit tag size. 
2. Argon2id with t=3 iterations, p=4 lanes, m=2^(16) (64 MiB of RAM), 128-bit salt, and 256-bit tag size.

I went with the second one, cause 2Gib of RAM seems harsh for a client-side app

2024-11-29 13:46 UTC, TamaraFinogina commented on test/unit/services/utils.passToHash.test.ts
> +    const iterations = 16777216;
this test is veeery slow, we can remove if it's a problem

2024-12-02 17:35 UTC, TamaraFinogina commented on src/app/auth/services/auth.service.ts
> +        token,
should be token or newToken here?

2024-12-03 15:38 UTC, CandelR commented on src/app/auth/services/auth.service.ts
> +        token,
None of them, it is a backend generated token to make the password change possible, this solution will not work for what you need

2024-12-03 15:46 UTC, CandelR requested changes

2024-12-03 15:46 UTC, CandelR commented on src/app/auth/services/auth.service.ts
> +        token,
You can use the `changePassword` function, but you will have to do it only the first time this change is made, so you don't have to call this endpoint every time you login.

2024-12-04 09:15 UTC, TamaraFinogina commented on src/app/auth/services/auth.service.ts
> +        token,
ok, I'll change it

2024-12-04 10:10 UTC, TamaraFinogina commented on src/app/auth/services/auth.service.ts
> +        token,
@CandelR Done

2024-12-04 17:17 UTC, TamaraFinogina commented on src/app/auth/services/auth.service.ts
>          token: token,
@CandelR This token would be wrong cause it was updated inside, no?

2024-12-05 07:54 UTC, CandelR requested changes
After hash change (password change with new hash) is not possible to access to Setting security section
![Screenshot 2024-12-05 at 08 48 35](https://github.com/user-attachments/assets/876791e8-8008-48a6-92d6-242ffa9e90e9)

2024-12-09 14:55 UTC, CandelR approved these changes

2024-12-09 15:01 UTC, CandelR commented
passed to draft so that it does not merge unintentionally

2024-12-11 09:31 UTC, CandelR reviewed
@larry-internxt Will this also affect [cli](https://github.com/internxt/cli) login?

2024-12-11 11:08 UTC, larryrider commented
> @larry-internxt Will this also affect [cli](https://github.com/internxt/cli) login?

@CandelR If the server will still accept the old hash, this change will not have any impact on the CLI login. However, it might be a good idea to reuse this code for the CLI as well. We could even consider integrating this into inxt-js or the inxt-sdk, whichever makes the most sense, so all the apps (including desktop) could use it.

2024-12-11 11:23 UTC, CandelR commented
> > @larry-internxt Will this also affect [cli](https://github.com/internxt/cli) login?
> 
> @CandelR If the server will still accept the old hash, this change will not have any impact on the CLI login. However, it might be a good idea to reuse this code for the CLI as well. We could even consider integrating this into inxt-js or the inxt-sdk, whichever makes the most sense, so all the apps (including desktop) could use it.

The backend does not accept both, it overwrites the new one, so it would be good if we could add this implementation to some internxt library to be able to share it on all platforms, since it also applies to mobile. Desktop does the login through the web, so there should be no problem, but if the suite of apps is going to grow we will need to have the code as accessible as possible to all platforms.
On top of that it will also be easier to maintain as there will only be one project where the code is located and the others will use it.

2025-05-30 09:12 UTC, closed without merging

2025-05-30 09:12 UTC, TamaraFinogina commented
Switched to backlog: https://inxt.atlassian.net/browse/PB-3079