[PB-3080] Add post-quantum (Kyber)
internxt/drive-web pull request #1373
Opened 2024-11-28 15:56 UTC by TamaraFinogina

**Add a post-quantum layer.**

Quantum computers will only be a problem for asymmetric encryption, which we use when we send encrypted mnemonics (ecc from OpenPGP in our case). The idea is to use hybrid encryption - ecc and KyberKEM - for sending the mnemonic. Thus, if ecc is broken or Kyber needs different parameters for security, the mnemonic is still safe.

For that, each user should additionally have a Kyber keys pair `(publicKyberKey, privateKyberKey)`. Then, we split mnenomic into two parts (`mnemonic = part1 XOR part2`) and encrypt `par1` with ecc and `part2` with Kyber. 

Encrypt:

```
(ciphertext, secret) await kem.encapsulate(publicKyberKey)
longSecret = await extendSecret(secret, len(mnemonic))
message = mnemonic XOR longSecret
eccCiphertext =  await openpgp.encrypt( message, publicKey)
send `(eccCiphertext, ciphertext)
```

Decrypt: 

```
secret  = await kem.decapsulate(ciphertext, privateKyberKey)
message  =  await openpgp.decrypt(eccCiphertext, privateKey)
longSecret = await extendSecret(secret, len(message))
mnemonic = message XOR longSecret
```

**NOTE 1:**  KyberKEM always outputs a fixed-length secret, but mnemonic can have different sizes. Hence, we extend it with the `extendSecret` function (that is just Blake3 hash).  It can also shrink the secret if needed, but usually mnemonic is bigger than the secret.

**NOTE 2:** During the migration period, we must support both old and new sharing methods. I've added a flag `hybridModeEnabled` to differentiate. But we can remove it and use ciphertext size or a prefix instead.

2024-12-11 09:04 UTC, CandelR requested changes

2024-12-11 09:04 UTC, CandelR commented on src/app/drive/components/ShareDialog/ShareDialog.tsx
> +      const hybridModeEnabled = isAdvancedShareItem(itemToShare.item) ? itemToShare?.item?.hybridModeEnabled : false;
Is the `hybridModeEnabled` field already added to the backend?

2024-12-11 09:04 UTC, CandelR commented on src/app/auth/services/auth.service.ts
> +    encPrivateKyberKey: aes.encrypt(privateKyberKeyBase64, password, getAesInitFromEnv()),
the `enc` of `encPrivateKyberKey` means encrypted? 
you could add the whole word to make the const name more descriptive

2024-12-11 15:44 UTC, TamaraFinogina commented on src/app/drive/components/ShareDialog/ShareDialog.tsx
> +      const hybridModeEnabled = isAdvancedShareItem(itemToShare.item) ? itemToShare?.item?.hybridModeEnabled : false;
No, Kyber PR is blocked by the backend. However, those fields are in SDK already

2024-12-17 09:25 UTC, closed without merging

2024-12-17 09:25 UTC, TamaraFinogina commented
there is another PR for kyber