[WT-1]: Feature/trash
internxt/drive-web pull request #441
Opened 2022-09-23 10:51 UTC by larry-internxt

- Added Trash View list
- Added move items to trash
- Added recover items from trash
- Added delete items permanently

Trash SDK uses .env REACT_APP_DRIVE_NEW_API_URL for backend

2022-11-03 15:56 UTC, fabioespinosa commented on src/app/core/config/app.json
> +}
EOF line

2022-11-03 16:06 UTC, fabioespinosa commented on src/app/drive/services/file.service/index.ts
> +// export function moveToTrash(items: DriveFileData[]): Promise<void> {
Is there a reason to maintain this commented code?

2022-11-03 16:06 UTC, fabioespinosa commented on src/app/drive/services/storage.service/index.ts
> +// export function deleteItems(items: DriveItemData[]): Promise<void> {
Or this commented code 🤔

2022-11-03 16:09 UTC, larry-disabled commented on src/app/drive/services/file.service/index.ts
> +// export function moveToTrash(items: DriveFileData[]): Promise<void> {
not really

2022-11-03 16:10 UTC, fabioespinosa requested changes
minor fixes and all good

2022-11-03 16:10 UTC, fabioespinosa commented on src/app/store/slices/storage/index.ts
> +      const folderIds = !Array.isArray(action.payload.folderIds) ? [action.payload.folderIds] : (action.payload.folderIds || Object.keys(state.levels).map((folderId) => parseInt(folderId)));
I would argue this is very confusing to read perhaps create an intermediate variable with a descriptive name or invert the ternary to not use `!`

2022-11-03 16:10 UTC, fabioespinosa commented on src/app/store/slices/storage/storage.thunks/deleteItemsThunk.ts
> +    // await storageService.deleteItems(itemsToDelete);
Any reason to leave this commented?

2022-11-08 09:00 UTC, sg-gs requested changes

2022-11-08 09:00 UTC, sg-gs commented on src/app/drive/components/DeleteItemsDialog/DeleteItemsDialog.tsx
> +        deleteItems(itemsToDelete);
I think there is an `await` missing here

2022-11-08 09:00 UTC, sg-gs commented on src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
>  //import shareService from 'app/share/services/share.service';
Remove this comment

2022-11-08 09:00 UTC, sg-gs commented on src/app/drive/components/DriveExplorer/DriveExplorerItem/index.tsx
>    item: DriveItemData;
Maybe checking the field `deleted` in `item` inside the explorer could be better than adding flags.

2022-11-08 09:00 UTC, sg-gs commented on src/app/drive/components/DriveItemDropdownActions/DriveItemDropdownActions.tsx
>  import UilFileInfoAlt from '@iconscout/react-unicons/icons/uil-file-info-alt';
Remove this comment

2022-11-08 09:00 UTC, sg-gs commented on src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
> +        restoreItemsFromTrash(itemsToMove, destinationFolderId, (destinationFolderId != currentFolderId) ? selectedFolderName : name, namePaths);
maybe missing an `await` here

2022-11-08 09:00 UTC, sg-gs commented on src/app/drive/services/file.service/uploadFile.ts
> +      plain_name: null
Be careful with this, maybe @CandelR or @fabioespinosa could say something about

2022-11-08 09:00 UTC, sg-gs commented on src/app/drive/services/folder.service.ts
> +  // deleteFolder,
remove this comment

2022-11-08 09:00 UTC, sg-gs commented on src/app/drive/types/index.ts
> +  plain_name: string | null;
the folder name should never be `null`

2022-11-08 09:00 UTC, sg-gs commented on src/use_cases/trash/get_trash.ts
> +const GetTrash = async (): Promise<void> => {
`getTrash`, let's use camelCase please

2022-11-08 09:00 UTC, sg-gs commented on src/use_cases/trash/move-items-to-trash.ts
> +const MoveItemsToTrash = async (itemsToTrash: DriveItemData[]): Promise<void> => {
same here, use camelCase

2022-11-08 09:00 UTC, sg-gs commented on src/use_cases/trash/recover-items-from-trash.ts
> +        //throw castedError;
remove comment

2022-11-08 09:00 UTC, sg-gs commented on src/use_cases/trash/recover-items-from-trash.ts
> +    //throw error;
remove comment

2022-11-08 09:00 UTC, sg-gs commented on src/use_cases/trash/recover-items-from-trash.ts
> +async function catchError(error) {
`handleError` could be a better naming. Also use err: unknown:
1. `err` is the name for an error variable as a convention in JS. 
2. unknown type is more semantic as seems that you are handling something that you are not sure about if is a common error.

Also, why is this function `async`?

2022-11-08 09:00 UTC, sg-gs commented on src/use_cases/trash/recover-items-from-trash.ts
> +    .then(response => trackMove(response, 'folder'))
If you use `async`, then use `await` and `try-catch`, otherwise remove `async` from the function declaration as returning a Promise is enough.

2022-11-08 09:00 UTC, sg-gs commented on src/use_cases/trash/recover-items-from-trash.ts
> +  return storageClient.moveFile(payload)
same here, use `async-await-try-catch` or use `then-catch` but not both.

2022-11-08 09:00 UTC, sg-gs commented on src/use_cases/trash/recover-items-from-trash.ts
> +const RecoverItemsFromTrash = async (itemsToRecover: DriveItemData[], destinationId, name?, namePaths?) => {
use camelCase

2022-11-08 09:00 UTC, sg-gs commented on src/use_cases/trash/recover-items-from-trash.ts
> +      moveFolder(item, item.id, destinationId).catch((err) => { if (err) { return err; } });
`await` missing here

2022-11-08 09:00 UTC, sg-gs commented on src/use_cases/trash/recover-items-from-trash.ts
> +      moveFile(item, item.fileId, destinationId, item.bucket).catch((err) => { if (err) { return err; } });
`await` missing here

2022-11-08 09:00 UTC, sg-gs commented on src/use_cases/trash/recover-items-from-trash.ts
> +      moveFile(item, item.fileId, destinationId, item.bucket).catch((err) => { if (err) { return err; } });
why `err` is not being handled?

2022-11-08 09:11 UTC, CandelR commented on src/app/drive/services/file.service/uploadFile.ts
> +      plain_name: null
Here should be the name in plain text, you can get it from the file with `file.name`. But I don't know if it is already deployed and will works. @fabioespinosa would know

2022-11-08 15:34 UTC, fabioespinosa approved these changes

2022-11-08 15:35 UTC, merged