[WT-263]  - Change way of reporting files and folders with same name uploaded
internxt/drive-web pull request #550
Opened 2023-01-05 16:38 UTC by CandelR

- Added logic and modal to handle name collision when uploading or moving elements

⚠️ WIP
- Opened in draft, cleaning code and doing little modifications. 
- Opened the PR to review the code from here.

2023-01-17 09:47 UTC, sg-gs approved these changes

2023-01-17 09:48 UTC, sg-gs commented
I request the @aboredvaro review this behavior to ensure all is fine.

2023-01-17 11:54 UTC, aboredvaro requested changes
- Must use the correct dialog from [name collision dialog branch](https://github.com/internxt/drive-web/tree/origin/feature/WT-263-name-collision-dialog) to ensure right design implementation and usability standards.
- When user selects "Keep both", everything goes as expected, but an error "Folder not found" pops up.
- When user selects "Replace current item" the folder corrupts, the item that is being replaced is moved to trash (this is ok), but then the new item that is uploaded never gets uploaded (a bunch of errors appear) and from that moment user can't upload anything to that parent folder. See video for example.

[Error video](https://send.internxt.com/download/0c9cdec7-f21e-4660-958a-6e25f92293c9?code=6b975ecda788889faac28e2d12ecba260417a0f2b0dea3cc76a71302d098a20b)

2023-01-17 13:30 UTC, CandelR commented
> Issues found:
> 
> * Must use the correct dialog from [name collision dialog branch](https://github.com/internxt/drive-web/tree/origin/feature/WT-263-name-collision-dialog) to ensure right design implementation and usability standards.
> * When user selects "Keep both", everything goes as expected, but an error "Folder not found" pops up.
> * When user selects "Replace current item" the folder corrupts, the item that is being replaced is moved to trash (this is ok), but then the new item that is uploaded never gets uploaded (a bunch of errors appear) and from that moment user can't upload anything to that parent folder. [See video for example](https://send.internxt.com/download/0c9cdec7-f21e-4660-958a-6e25f92293c9?code=6b975ecda788889faac28e2d12ecba260417a0f2b0dea3cc76a71302d098a20b).

> @aboredvaro 
Okay, I will check the branch dialogue and replace the current one.

- Regarding the errors on the "Keep both" and "Replace current item" it is a matter of Vercel environment variables not being correct. I check it also because apparently you can't upload files in the Vercel Preview and it probably has to do with the same thing, a configuration error in the Preview.

2023-01-18 15:59 UTC, aboredvaro requested changes

2023-01-18 15:59 UTC, aboredvaro commented on src/app/drive/components/DriveExplorer/DriveExplorer.tsx
> +                      <p>Test name collision</p>
Remove this testing menu item
<img width="281" alt="Screenshot 2023-01-18 at 16 57 33" src="https://user-images.githubusercontent.com/34165099/213224533-f1d04c25-fabb-4f12-84e5-c1e61d786446.png">

2023-01-19 09:58 UTC, aboredvaro approved these changes

2023-01-19 14:48 UTC, merged