[WT-286]: feat/add lazy loading to photo library
internxt/drive-web pull request #585
Opened 2023-02-13 11:10 UTC by rafijv

Improved user experience by allowing scrolling while the rest of the images load.

2023-02-14 11:17 UTC, CandelR approved these changes
@aboredvaro check if the skeleton when is loading more photos accomplish the design requirements

2023-02-14 13:07 UTC, aboredvaro commented
> 

Loading skeleton is good, but the problem is still showing the full sized photos (previews) instead of the photo/video smaller thumbnails. Load times will improve dramatically by showing thumbnails. I've attached a video to show how laggy it can get with only a few photos (same performance both on dev and prod environments):


https://user-images.githubusercontent.com/34165099/218747244-2958ad0b-e080-4f85-8007-4200a3b5126f.mov

2023-02-14 13:24 UTC, aboredvaro requested changes
Loading skeleton is good, but the problem is still showing the full sized photos (previews) instead of the photo/video smaller thumbnails. Load times will improve dramatically by showing thumbnails instead of previews (smaller image sizes). I've attached a video to show how laggy it can get with only a few photos (same performance both on dev and prod environments):

https://user-images.githubusercontent.com/34165099/218747244-2958ad0b-e080-4f85-8007-4200a3b5126f.mov

2023-02-15 08:42 UTC, aboredvaro approved these changes

2023-02-15 08:42 UTC, merged