[WT-278] feature/Right click gesture
internxt/drive-web pull request #601
Opened 2023-02-20 15:05 UTC by CandelR

- Added context menu to Drive, Recents, Backups, Shared Links and Trash items and views

2023-02-20 15:58 UTC, sg-gs requested changes

2023-02-20 15:58 UTC, sg-gs commented on src/app/backups/components/BackupList/BackupList.tsx
> +    selectedBackups.forEach(async (backup) => dispatch(backupsThunks.deleteBackupThunk(backup)));
`async` usage is not required inside forEach as you are not using `await`

2023-02-20 15:58 UTC, sg-gs commented on src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.tsx
> +      // onContextMenu={onItemRightClicked}
Remove this comment

2023-02-20 15:58 UTC, sg-gs commented on src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.tsx
> +      {/* <div className="box-content flex w-0.5/12 items-center justify-start pl-3">
Remove this comment

2023-02-20 15:58 UTC, sg-gs commented on src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.tsx
> +      {/* <div className="flex w-1/12 items-center">
Remove this comment

2023-02-20 15:58 UTC, sg-gs commented on src/app/drive/components/EditItemNameDialog/EditItemNameDialog.tsx
> +          return e;
This return is not required as you are not using the error

2023-02-21 08:40 UTC, sg-gs approved these changes

2023-02-21 13:38 UTC, aboredvaro requested changes
Issues found:
1. Inconsistent side, top and bottom spacing between lists, follow the [design spacing](https://www.figma.com/file/62hpKnJYlxUN77HUECXAlF/Drive-Web?node-id=3390%3A34184&t=XqLHODSQfWvvyDfI-11).
2. Keyboard shortcuts should work without the right-click menu open too.
3. (Bug) When a **folder** is selected and user taps “enter” on the keyboard, the preview dialog is opened with the name of the folder. When a user taps “enter” on a selected **folder** it should open the folder itself, not the preview.
4. When a user has multiple items selected and opens the right-click menu, "{X} items selected" is not an actionable item, it should be a <div/> like the separators.
5. Some icons in the right-click menu are not the same as in Figma (the download icon, for example), please check them [here](https://www.figma.com/file/62hpKnJYlxUN77HUECXAlF/Drive-Web?node-id=3465%3A72158&t=XqLHODSQfWvvyDfI-11).
6. The three-dot menu is hidden when user opens it on the last item of the list, it should behave similar to right-click menu when it is close to the edges of the screen (top and bottom).
7. When a folder is selected, the option “Open preview” should not appear (only on files), this happens both on three-dot and right-click menus.
8. (Bug) When the user clicks the three-dot icon of an unselected item, select the item and open the three-dot menu. [Check the behavior here](https://inxt.atlassian.net/wiki/spaces/DESIGN/pages/72941572/Right+click#Behavior).
9. On backups section, the empty state is inside the loading list. We need to separate two things: loading list (skeleton) and [empty state](https://www.figma.com/file/62hpKnJYlxUN77HUECXAlF/Drive-Web?node-id=3465%3A42434&t=XqLHODSQfWvvyDfI-11).
10. Drive's list "icon inline actions" (Download, Get link and Move to trash) should be removed since they are replaced by the right-click menu.
11. When user clicks "Rename", it should not use the inline input in the list, it should use the rename dialog.
12. (Bug) When user presses "⬆+F" to open the "New folder" dialog, it writes an "F" at the end of the dialog input. Same happens with the rename dialog when pressing "R".

(Sent a detailed video to Ramón via DM in Slack for better understanding)

2023-02-22 17:45 UTC, aboredvaro approved these changes

2023-02-23 13:08 UTC, sg-gs approved these changes

2023-02-23 14:31 UTC, merged