[WT-327]: Feat/top action bar in file preview wt 327
internxt/drive-web pull request #610
Opened 2023-02-21 19:05 UTC by masterprog-cmd

Top bar actions added with the following options:
* Copy link
* Share settings (Dialog)
* Delete link
* Rename
* Move
* Download
* Moved to trash

2023-02-23 12:50 UTC, sg-gs approved these changes

2023-02-23 14:03 UTC, aboredvaro requested changes

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/FileViewer.tsx
> +      onClick={onDownload}
Missing accessible text `title="Download"`
(add translations too)

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/FileViewer.tsx
> +    className={'z-10 mt-3 flex h-10 flex-shrink-0 flex-row items-center justify-end space-x-2 rounded-lg bg-primary'}
Should be`h-11` instead of `h-10`

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/FileViewer.tsx
> +                          ease-in-out hover:bg-opacity-10 focus:bg-opacity-5"
Change for `flex h-11 w-11 cursor-pointer flex-row items-center justify-center rounded-lg bg-white bg-opacity-0 font-medium transition duration-50 ease-in-out hover:bg-opacity-10 focus:bg-opacity-5 focus-visible:bg-opacity-5 outline-none`

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/FileViewer.tsx
> +      <UilImport height="20" width="20" />
Change `height="20" width="20"` for `size={20}`

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/components/TopBarActions.tsx
> +        <UilImport height="20" width="20" />
Change `height="20" width="20"` for `size={20}`

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/FileViewer.tsx
> -              onClick={() => changeFile('prev')}
Missing accessible text `title="Previous"`
(add translations too)

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/FileViewer.tsx
> +                onClick={() => changeFile('prev')}
Missing accessible text `title="Next"`
(add translations too)

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/components/TopBarActions.tsx
> +        onClick={onDownload}
Missing accessible text `title="Download"`
(add translations too)

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/components/TopBarActions.tsx
> +      className={`${background} z-10 mt-3 flex h-10 flex-shrink-0 flex-row items-center justify-end space-x-2 rounded-lg`}
Should be `h-11` instead of `h-10`

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/components/TopBarActions.tsx
> +                          ease-in-out hover:bg-opacity-10 focus:bg-opacity-5"
Change for `flex h-11 w-11 cursor-pointer flex-row items-center justify-center rounded-lg bg-white bg-opacity-0 font-medium transition duration-50 ease-in-out hover:bg-opacity-10 focus:bg-opacity-5 focus-visible:bg-opacity-5 outline-none`

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/components/TopBarActions.tsx
> +                          ease-in-out hover:bg-opacity-10 focus:bg-opacity-5"
Change for `flex h-11 w-11 cursor-pointer flex-row items-center justify-center rounded-lg bg-white bg-opacity-0 font-medium transition duration-50 ease-in-out hover:bg-opacity-10 focus:bg-opacity-5 focus-visible:bg-opacity-5 outline-none`

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/components/TopBarActions.tsx
> +            <DotsThree height="20" width="20" />
Change for `<DotsThree weight="bold" size={20} />`

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/FileViewer.tsx
>                  <span>{translate('error.noFilePreview')}</span>
Missing updated design for “No preview available”

<img width="1022" alt="Screenshot 2023-02-23 at 14 53 37" src="https://user-images.githubusercontent.com/34165099/220927273-f5820f5c-3620-450a-babf-b0b2ffd3018c.png">

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/components/TopBarActions.tsx
> +                      onClick={onMoveButtonClicked}
When user is inside the preview view, opens the mode dialog and presses `ESC`, it should close the move dialog, not the preview view and leave the move dialog open.

(Close the most recent dialog opened first, if user opens `Preview → Move dialog → New folder dialog` it should close in reverse order when clicking `ESC` : `New folder dialog → Move dialog → Preview`)

https://user-images.githubusercontent.com/34165099/220928559-5caadb76-daf2-4362-a2f2-1047d11ddc1f.mov

2023-02-23 14:03 UTC, aboredvaro commented on src/app/drive/components/FileViewer/FileViewer.tsx
>                </Dialog.Title>
File name does not truncate correctly

<img width="1455" alt="Screenshot 2023-02-23 at 14 35 12" src="https://user-images.githubusercontent.com/34165099/220929350-d1cf4492-2eaf-4f4b-9ae4-71167ed8bbe8.png">

2023-02-27 09:09 UTC, sg-gs approved these changes

2023-02-27 10:44 UTC, CandelR approved these changes

2023-02-27 11:09 UTC, CandelR approved these changes

2023-02-27 11:09 UTC, merged