[WT-358] bugfix/Fix file preview option issues
internxt/drive-web pull request #641
Opened 2023-03-20 16:50 UTC by CandelR

- Fixed erroneous behaviour on actions of a shared file in preview

2023-03-20 17:45 UTC, sg-gs requested changes

2023-03-20 17:45 UTC, sg-gs commented on src/app/drive/components/FileViewer/components/TopBarActions.tsx
> +            window.location.href = process.env.REACT_APP_HOSTNAME + '/login';
why not use `navigationService.push('/login')`?

2023-03-21 15:57 UTC, CandelR commented on src/app/drive/components/FileViewer/components/TopBarActions.tsx
> +            window.location.href = process.env.REACT_APP_HOSTNAME + '/login';
Because I am not sure if it will work because it changes the domain and I have put the same navigation as there is ShareLayout.tsx to the login view in drive.

2023-03-22 17:54 UTC, sg-gs approved these changes

2023-03-22 17:58 UTC, merged