[_]: fix/Buy lifetime plan with coupon when user has subscription
internxt/drive-web pull request #677
Opened 2023-04-26 11:03 UTC by masterprog-cmd

Now, user can buy a lifetime plan from internxt.com/lifetime with the discount when he has a subscription activated.

2023-04-26 13:30 UTC, CandelR requested changes

2023-04-26 13:30 UTC, CandelR commented on src/app/payment/views/CheckoutView/CheckoutPlanView.tsx
> +              }));
As the only difference the object has is the coupon, perhaps adding an interface to define the type and putting the code like this makes it a bit clearer what changes there are between one structure and the other.
Adding the interface:
```
interface CheckoutOptions {
  price_id: string;
  coupon_code?: string;
  success_url: string;
  cancel_url: string;
  customer_email: string;
  mode: string;
}
```
```suggestion
          const checkoutOptions: CheckoutOptions = {
            price_id: planId,
            success_url: `${window.location.origin}/checkout/success`,
            cancel_url: 'https://drive.internxt.com/preferences?tab=plans',
            customer_email: user.email,
            mode: mode,
          };

          if (coupon) {
            checkoutOptions.coupon_code = coupon;
          }

          response = await paymentService.createCheckoutSession(checkoutOptions);
```

2023-04-27 14:30 UTC, masterprog-cmd commented on src/app/payment/views/CheckoutView/CheckoutPlanView.tsx
> +              }));
Done

2023-04-27 14:39 UTC, CandelR approved these changes

2023-04-27 16:13 UTC, merged