[PB-687] feat/calculate-bandwith
internxt/drive-web pull request #754
Opened 2023-07-26 08:17 UTC by miguelsw

- Add upload and download bandwith to send in track options.

2023-07-26 08:21 UTC, sg-gs requested changes

2023-07-26 08:21 UTC, sg-gs commented on src/app/drive/services/download.service/downloadFile.ts
> +  console.log('2');
Remove this `console.log`

2023-07-26 08:21 UTC, sg-gs commented on src/app/drive/services/network.service/index.ts
> +  private _startTime: number;
We are already using `private` in TypeScript, the `_` convention is not required

2023-07-26 08:21 UTC, sg-gs commented on src/app/drive/services/network.service/index.ts
> +  getStartTime() {
use getters and setters

2023-08-03 06:39 UTC, CandelR commented on src/app/drive/services/network.service/index.ts
> +  set sise(size: number) {
typo: `sise` -> `size`

2023-08-03 06:39 UTC, CandelR commented on src/app/drive/services/folder.service.ts
>            console.log({ trackingDownloadProperties });
Remove this console.log

2023-08-04 13:27 UTC, CandelR approved these changes

2024-03-13 12:24 UTC, SimonGodefroid commented on src/app/drive/services/network.service/index.ts
> +    const totalMB = this.size / 1024 / 1024; //MB
```suggestion
    const totalMB = this.size / 1024 / 1024; // MB
```

2024-11-28 15:08 UTC, sg-gs commented
Not tracking this anymore, closing @internxt/web

2024-11-28 15:08 UTC, closed without merging