[PB-748]: Feat/bump tailwind css
internxt/drive-web pull request #901
Opened 2023-10-26 09:36 UTC by masterprog-cmd

Update the TailwindCSS version to the latest one

2023-10-31 14:48 UTC, aboredvaro requested changes
Firstly, great work @masterprog-cmd 👏🏻👏🏻👏🏻

At first sight it looks like everything CSS related works, however the tailwindcss.config.json still needs to be upgraded, here's a guide on how to do it: https://tailwindcss.com/docs/upgrade-guide

On the other side, since grid view was improved, I propose to solve a bug too. The bug consist on the right click on grid view, it should open the same context menu as in list mode.

2023-11-02 08:57 UTC, masterprog-cmd commented
> Firstly, great work @masterprog-cmd 👏🏻👏🏻👏🏻
> 
> At first sight it looks like everything CSS related works, however the tailwindcss.config.json still needs to be upgraded, here's a guide on how to do it: https://tailwindcss.com/docs/upgrade-guide
> 
> On the other side, since grid view was improved, I propose to solve a bug too. The bug consist on the right click on grid view, it should open the same context menu as in list mode.

I've fixed the bug @aboredvaro !

2023-11-02 11:19 UTC, aboredvaro commented on tailwind.config.js
Variants should be removed too

https://tailwindcss.com/docs/upgrade-guide#remove-variant-configuration

2023-11-09 13:59 UTC, aboredvaro requested changes

2023-11-09 13:59 UTC, aboredvaro commented on src/app/shared/components/Empty/Empty.tsx
> +            ? 'mt-5 bg-primary/10 hover:bg-primary/15 active:bg-primary/20'
`hover:bg-primary/15 active:bg-primary/20` should be removed from this line and added back to the line 28

2023-11-09 14:06 UTC, aboredvaro requested changes

2023-11-09 14:06 UTC, aboredvaro commented on src/app/drive/components/DriveItemInfoMenu/DriveItemInfoMenu.tsx
> +          className="whitespace-nowrap\ mx-3 block
Remove the "\" at the end of `whitespace-nowrap\`

2023-11-10 10:12 UTC, aboredvaro approved these changes

2023-11-13 10:41 UTC, merged