[PB-1367]: feat/update Empty state inside the folders
internxt/drive-web pull request #952
Opened 2023-12-04 16:09 UTC by masterprog-cmd

* If the shared view is empty, we show the Empty status we have now. 

* If the user is a folder owner or editor, then we show an Empty state saying that the user can drag and drop files or can use the upload button.

* If the user is a viewer, then we only show the empty folder icon and the title saying that the folder is empty, without the possibility to upload files.

2023-12-04 16:37 UTC, aboredvaro approved these changes

2023-12-05 08:07 UTC, CandelR requested changes

2023-12-05 08:07 UTC, CandelR commented on src/app/share/views/SharedLinksView/SharedView.tsx
> +  const emptyState = {
Extract it to a separate component in order to not add more unnecessary code in the view.

2023-12-07 07:35 UTC, CandelR requested changes

2023-12-07 07:35 UTC, CandelR commented on src/app/drive/components/EmptySharedView/EmptySharedView.tsx
> +const EmptySharedView = ({ onUploadFileButtonClicked, sharedNamePath, isCurrentUserViewer }) => {
As it is specific to the SharedView, add it to the folder that belongs to this view, in share/components.

2023-12-13 10:06 UTC, CandelR approved these changes

2023-12-13 11:00 UTC, merged